[package]
name = "winix"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.39"
colored = "3.0.0"
sysinfo = "0.35.1"
winapi = "0.3.9"
windows-acl = "0.3.0"
windows-sys = "0.59.0"

[dev-dependencies]
tempfile = "3.8"
